import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
 container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
 },
 contentContainer: {
    width: '100%',
    backgroundColor: '#fff',
    alignItems: 'center',
    padding: 5,
 }, 
 picture: {
    width: '100%',
    height: 230,
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
 },
 placeName: {
    fontFamily: 'Roboto-Thin',
    fontSize: 25,
    alignSelf: 'flex-start',
    color: '#000',
    marginTop: 10,
    marginLeft: 10,
 },
 placeType: {
  fontFamily: 'roboto-bold',
  fontSize: 18,
  alignSelf: 'flex-start',
  color: '#000',
},
 placeAddress: {
    fontFamily: 'Roboto-Regular',
    fontSize: 18,
    alignSelf: 'flex-start',
    color: '#000',
    marginTop: 10,
    marginLeft: 10,
 },
 blockHeader: {
    fontFamily: 'Roboto-Regular',
    fontSize: 18,
    textAlign: 'center',
    color: '#000',
    marginBottom: 4,
 },

 blueCircut: {
    alignSelf: 'center', 
    backgroundColor: '#5682a3', 
    borderRadius: 30, 
    padding: 10, 
    width: 60, 
    height: 60, 
    justifyContent: 'center'
 },
 placePrice: {   
    fontFamily: 'roboto-bold',
    fontSize: 15,
    textAlign: 'center',
    color: '#fff',
 },
 placePriceValute: {   
  fontFamily: 'roboto-bold',
  fontSize: 12,
  textAlign: 'center',
  color: '#fff',
},
 placeDescription: {
    padding:5,
    fontFamily: 'Roboto-Regular',
    fontSize: 15,
    textAlign: 'center',
    color: '#000',
    fontStyle: 'italic',
 },
 placeHistory: {
    fontFamily: 'Roboto-Regular',
    fontSize: 15,
    fontStyle: 'italic',
    textAlign: 'center',
    color: '#000',
    padding:5,
 },
 contactButtons:{
  flexDirection: 'row', 
  justifyContent: 'center', 
  alignItems: 'center', 
  backgroundColor: '#fff',
  borderRadius:15,
  paddingVertical: 3,
  paddingHorizontal: 10,
  marginTop: 5,
  borderColor: '#5682a3',
  borderWidth: 1,
 },
 contactLink:{
  flexDirection: 'row', 
  justifyContent: 'center', 
  alignItems: 'center', 
  backgroundColor: '#fff',
  borderRadius:15,
  paddingVertical: 3,
  paddingHorizontal: 10,
  marginTop: 5,
 },
 contactText:{
  fontFamily: 'Roboto-Regular',
  fontSize: 18,
  textAlign: 'center',
  color: '#000',
 },
 contactIcon:{
  width: 20, 
  height: 20, 
  resizeMode: 'contain', 
  marginRight: 4,
 },
});